language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAJQAWZFS4IG25XKIQ
  secret_access_key:
    secure: AgaZAN4xCgimmx/q6Rl5hr8WZowzDRV3BG1dIMduAf3MZq2ACvDRl7CiKZN2bvFYHJW1IyD8vqFPxjULd0d5HJFnUShn2x+X7HIHXAALeMtokIYl5FNy6uoz8mqD2AaE+TxGqcEf6sbV5KaxuYUWVZrdGuacqwSy02Dkst85lzRa27z3RJmlbYVvI/4J065/gszpRddh8cew5qD5qrlnA32GJAmvDXPRI/QmFBRQ61gGjYwNSWP5m4cTHP4KWktFCb/1+VPuLk2IB/n0IKzc8xJmzGpUwASRPHCfvVpWcskjVeeAhKdQkP2Ipm8Xa6zZMvRjmCOyR79dn462+i/xNFOSYkPKsrcmRZ19Oobs7iysWfNUXp8KJqJKqMUNNpVhIDr+sHGYZnI/1/Yl650npg9jHtwlq5A+6t6k0sUR/EiTI0ib+9+IPhHwwNdoSxDMaAw3HjeUC2XVKyX3QW4rWVX3Zxx5pU4/+BuHNR5rN1Y0m8AMrcWja2PQI9r6W7jDXOooltZBQI7XeXhQicSY+wZ+2fiFIUMJ5RufDM6tB4C35LuNHeUAJM9WC6/+4d9opByAyCmqwmY9b3che7LZ1z9lDq00nvBKreK+umrBg4c+tQ6ZwPxbIWW24ZxJPg9PpGu1W/G8oBOujm+WlGN0jGFZBaBGURu9eLCWywU2xk4=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: kf-dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/kf-dictionary
    all_branches: true
