language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- ./run_tests.sh
deploy:
  provider: s3
  access_key_id: AKIAJN3J2IYKPWYQPXEA
  secret_access_key:
    secure: hvBxH/tyn8w0KzPBXNKG9Mm4cFoQcUx4uBllxjKbjaPlwqOdROX5SIPXV+vosfBvKf9h6zBiFVrzZYi3FXd9WtqPNW4rToPsLrCQ3VzZpV3YQlCGvD8v1puRhJifTVlqH1OV2zFtUyM35UBTwY4u0IErVwFj5K4ZVQ33xeAUT/u6jPEC6/NPqBtdVkQ017exaKmmQuwK4o8AztEaAxKV61KmRBeyWEy5jrk9V1ofjqpJNDp1R9V9pMaqzHsCVm/8Fg4PnoJoOClAn/2utjH7FZr8CPRWexn6NNBcU58KftR4WbamL0hhirxcYMOZKyUltUbfpGT11Eh2fe9HVLHQOcsDO8ax77vakrFPRrM/mmsOvUVjvxpFP68pQ+4JOPLr5YHc9Yis7byJQBzgLWwhlFTfbV4vLHDJdzyTs5RYeh+d0cj/GhZl/99qJ9Coiu+O3qpzXq8Ynk/6iluNK8to8Weu1tQRhy6SNhBcb2Udx57yVHOtOb9+xBw+xVdm2MwYVJqjiwjQyj9AAd7XyrCogQ6tHlcsPOkHFvYOMgpekFpoqkOV9TKs4Hn7XzcyB7YwPvMVG3kA2xJaLdDPGdEjWTudlIL4cHQzGCIepFtGv1+YfkD4vZqjRoIznf5V50vRR+buz2/SULbQAAOUBr8j81vlr0N9A9MHxJC6ZGjE2t0=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: kf-dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: kids-first/kf-dictionary
    all_branches: true
